name: eth_abi_codec
description: decode and encode for eth contract call
version: 0.2.1
homepage: https://github.com/nbltrust/dart-eth-abi-codec

dependencies:
  convert: ^3.0.2
  pointycastle: ^3.6.2
  typed_data: ^1.3.1

dev_dependencies:
  test: ^1.5.1

environment:
  sdk: '>=2.12.0 <3.0.0'
